#ifndef VERSION_H
#define VERSION_H

#define MAJIN_VERSION_MAJOR 1
#define MAJIN_VERSION_MINOR 0
#define MAJIN_VERSION_PATCH 0

// Ajout du suffixe BETA
#define MAJIN_VERSION_NAME "Cyber-Awakening (BETA)"
#define MAJIN_BUILD_DATE __DATE__ " " __TIME__

#define STR_HELPER(x) #x
#define STR(x) STR_HELPER(x)

#define MAJIN_FW_VERSION "v" STR(MAJIN_VERSION_MAJOR) "." STR(MAJIN_VERSION_MINOR) "." STR(MAJIN_VERSION_PATCH) "-BETA"

#endif